language: java
install: true

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "gavarava-github"
    token: $SONAR_TOKEN

git:
  depth: false

script:
  - ./gradlew
  - sonar-scanner
  - docker build -t rockpaperscissors:0.0.1  .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

