language: java
install: true

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "gavarava-github"
    token: $SONAR_TOKEN

git:
  depth: false

script:
  - ./gradlew --no-build-cache
  - sonar-scanner