language: java
install: true

jdk:
  - openjdk8

script:
  - ./gradlew clean build
  - ./gradlew sonarqube \
      -Dsonar.projectKey=gavarava_rockpaperscissors \
      -Dsonar.organization=gavarava-github \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=rockpaperscissors
