management:
  port: 9000
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000
---
spring:
  profiles: development

logging:
  level:
    root: INFO
    org.springframework.web: INFO

---
spring:
  profiles: staging

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
